# The beauty of our CI setup is that it will build Dockerfile and set variables from the Dockerfile
# by https://pascalandy.com at https://firepress.org
# GNU v3 https://github.com/firepress-org/ghostfire/blob/master/LICENSE

name: multi_arch

on:
  schedule:
    - cron: "0 7 * * *"
  workflow_dispatch:

defaults:
  run:
    shell: "bash -Eeuo pipefail -x {0}"

env:
  DOCKERFILE: Dockerfile

jobs:
  # ----------------------------------------------
  # SET VARIABLES
  # More context about the way we set variables https://github.com/firepress-org/ghostfire/issues/46
  # ----------------------------------------------
  myvars:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: zcong1993/setup-timezone@v1.1.2
        with:
          timezone: America/Montreal
      - name: Github Actions system status
        uses: crazy-max/ghaction-github-status@v3.0.0
        with:
          overall_threshold: minor
          git_threshold: degraded_performance
          actions_threshold: operational
      - name: Create dir for our varz
        run: mkdir -pv ~/varz
      - name: EDGE | Set BRANCH_NAME
        if: github.ref != 'refs/heads/master'
        run: |
          echo "edge" > ~/varz/BRANCH_NAME
      - name: MASTER | Set BRANCH_NAME
        if: github.ref == 'refs/heads/master'
        run: |
          echo "stable" > ~/varz/BRANCH_NAME
      - name: Define and save variables to disk
        run: |
          cat ${{ env.DOCKERFILE }} | grep APP_NAME= | head -n 1 | grep -o '".*"' | sed 's/"//g' > ~/varz/APP_NAME
          cat ${{ env.DOCKERFILE }} | grep DOCKERHUB_USER= | head -n 1 | grep -o '".*"' | sed 's/"//g' > ~/varz/DOCKERHUB_USER
          cat ${{ env.DOCKERFILE }} | grep GITHUB_ORG= | head -n 1 | grep -o '".*"' | sed 's/"//g' > ~/varz/GITHUB_ORG
          cat ${{ env.DOCKERFILE }} | grep GITHUB_REGISTRY= | head -n 1 | grep -o '".*"' | sed 's/"//g' > ~/varz/GITHUB_REGISTRY
          echo "$(cat ~/varz/DOCKERHUB_USER)/$(cat ~/varz/APP_NAME)" > ~/varz/DKR_PREFIX
          echo "ghcr.io/$(cat ~/varz/GITHUB_ORG)/$(cat ~/varz/GITHUB_REGISTRY)/$(cat ~/varz/APP_NAME)" > ~/varz/GPR_PREFIX
          cat ${{ env.DOCKERFILE }} | grep VERSION= | head -n 1 | grep -o '".*"' | sed 's/"//g' > ~/varz/VERSION
          git rev-parse --short HEAD > ~/varz/SHORT_HASH_COMMIT
          date "+%Y-%m-%d_%HH%M" > ~/varz/DATE
          echo "$(cat ~/varz/BRANCH_NAME)_$(cat ~/varz/VERSION)_ci_$(cat ~/varz/SHORT_HASH_COMMIT)" > ~/varz/VERSION_CI
          echo "$(cat ~/varz/BRANCH_NAME)_$(cat ~/varz/VERSION)" > ~/varz/VERSION_BRANCH
          echo "$(cat ~/varz/BRANCH_NAME)_$(cat ~/varz/VERSION)_$(cat ~/varz/SHORT_HASH_COMMIT)" > ~/varz/VERSION_HASH_ONLY
          echo "$(cat ~/varz/BRANCH_NAME)_$(cat ~/varz/VERSION)_$(cat ~/varz/SHORT_HASH_COMMIT)_$(cat ~/varz/DATE)" > ~/varz/VERSION_HASH_DATE
          echo "$(cat ~/varz/APP_NAME):$(cat ~/varz/BRANCH_NAME)_$(cat ~/varz/VERSION)_$(cat ~/varz/SHORT_HASH_COMMIT)" > ~/varz/_NOTI_MESSAGE
          echo "$(cat ~/varz/DKR_PREFIX):$(cat ~/varz/BRANCH_NAME)" > ~/varz/TAG_DKR_BRANCH_NAME
          echo "$(cat ~/varz/DKR_PREFIX):$(cat ~/varz/VERSION_BRANCH)" > ~/varz/TAG_DKR_VERSION_BRANCH
          echo "$(cat ~/varz/DKR_PREFIX):$(cat ~/varz/VERSION_HASH_ONLY)" > ~/varz/TAG_DKR_VERSION_HASH_ONLY
          echo "$(cat ~/varz/DKR_PREFIX):$(cat ~/varz/VERSION_HASH_DATE)" > ~/varz/TAG_DKR_VERSION_HASH_DATE
          echo "$(cat ~/varz/GPR_PREFIX):$(cat ~/varz/BRANCH_NAME)" > ~/varz/TAG_GPR_BRANCH_NAME
          echo "$(cat ~/varz/GPR_PREFIX):$(cat ~/varz/VERSION_BRANCH)" > ~/varz/TAG_GPR_VERSION_BRANCH
          echo "$(cat ~/varz/GPR_PREFIX):$(cat ~/varz/VERSION_HASH_ONLY)" > ~/varz/TAG_GPR_VERSION_HASH_ONLY
          echo "$(cat ~/varz/GPR_PREFIX):$(cat ~/varz/VERSION_HASH_DATE)" > ~/varz/TAG_GPR_VERSION_HASH_DATE

      - name: Upload variables as artifact
        uses: actions/upload-artifact@master
        with:
          name: variables_on_disk
          path: ~/varz
      - name: Expose variables to all jobs
        id: myvars
        run: |
          echo "::set-output name=BRANCH_NAME::$(cat ~/varz/BRANCH_NAME)"
          echo "::set-output name=APP_NAME::$(cat ~/varz/APP_NAME)"
          echo "::set-output name=DOCKERHUB_USER::$(cat ~/varz/DOCKERHUB_USER)"
          echo "::set-output name=GITHUB_ORG::$(cat ~/varz/GITHUB_ORG)"
          echo "::set-output name=GITHUB_REGISTRY::$(cat ~/varz/GITHUB_REGISTRY)"
          echo "::set-output name=DKR_PREFIX::$(cat ~/varz/DKR_PREFIX)"
          echo "::set-output name=GPR_PREFIX::$(cat ~/varz/GPR_PREFIX)"
          echo "::set-output name=VERSION::$(cat ~/varz/VERSION)"
          echo "::set-output name=SHORT_HASH_COMMIT::$(cat ~/varz/SHORT_HASH_COMMIT)"
          echo "::set-output name=DATE::$(cat ~/varz/DATE)"
          echo "::set-output name=VERSION_CI::$(cat ~/varz/VERSION_CI)"
          echo "::set-output name=VERSION_BRANCH::$(cat ~/varz/VERSION_BRANCH)"
          echo "::set-output name=VERSION_HASH_ONLY::$(cat ~/varz/VERSION_HASH_ONLY)"
          echo "::set-output name=VERSION_HASH_DATE::$(cat ~/varz/VERSION_HASH_DATE)"
          echo "::set-output name=_NOTI_MESSAGE::$(cat ~/varz/_NOTI_MESSAGE)"
          echo "::set-output name=TAG_DKR_BRANCH_NAME::$(cat ~/varz/TAG_DKR_BRANCH_NAME)"
          echo "::set-output name=TAG_DKR_VERSION_BRANCH::$(cat ~/varz/TAG_DKR_VERSION_BRANCH)"
          echo "::set-output name=TAG_DKR_VERSION_HASH_ONLY::$(cat ~/varz/TAG_DKR_VERSION_HASH_ONLY)"
          echo "::set-output name=TAG_DKR_VERSION_HASH_DATE::$(cat ~/varz/TAG_DKR_VERSION_HASH_DATE)"
          echo "::set-output name=TAG_GPR_BRANCH_NAME::$(cat ~/varz/TAG_GPR_BRANCH_NAME)"
          echo "::set-output name=TAG_GPR_VERSION_BRANCH::$(cat ~/varz/TAG_GPR_VERSION_BRANCH)"
          echo "::set-output name=TAG_GPR_VERSION_HASH_ONLY::$(cat ~/varz/TAG_GPR_VERSION_HASH_ONLY)"
          echo "::set-output name=TAG_GPR_VERSION_HASH_DATE::$(cat ~/varz/TAG_GPR_VERSION_HASH_DATE)"
    outputs:
      BRANCH_NAME: ${{ steps.myvars.outputs.BRANCH_NAME }}
      APP_NAME: ${{ steps.myvars.outputs.APP_NAME }}
      DOCKERHUB_USER: ${{ steps.myvars.outputs.DOCKERHUB_USER }}
      GITHUB_ORG: ${{ steps.myvars.outputs.GITHUB_ORG }}
      GITHUB_REGISTRY: ${{ steps.myvars.outputs.GITHUB_REGISTRY }}
      DKR_PREFIX: ${{ steps.myvars.outputs.DKR_PREFIX }}
      GPR_PREFIX: ${{ steps.myvars.outputs.GPR_PREFIX }}
      VERSION: ${{ steps.myvars.outputs.VERSION }}
      SHORT_HASH_COMMIT: ${{ steps.myvars.outputs.SHORT_HASH_COMMIT }}
      DATE: ${{ steps.myvars.outputs.DATE }}
      VERSION_CI: ${{ steps.myvars.outputs.VERSION_CI }}
      VERSION_BRANCH: ${{ steps.myvars.outputs.VERSION_BRANCH }}
      VERSION_HASH_ONLY: ${{ steps.myvars.outputs.VERSION_HASH_ONLY }}
      VERSION_HASH_DATE: ${{ steps.myvars.outputs.VERSION_HASH_DATE }}
      _NOTI_MESSAGE: ${{ steps.myvars.outputs._NOTI_MESSAGE }}
      TAG_DKR_BRANCH_NAME: ${{ steps.myvars.outputs.TAG_DKR_BRANCH_NAME }}
      TAG_DKR_VERSION_BRANCH: ${{ steps.myvars.outputs.TAG_DKR_VERSION_BRANCH }}
      TAG_DKR_VERSION_HASH_ONLY: ${{ steps.myvars.outputs.TAG_DKR_VERSION_HASH_ONLY }}
      TAG_DKR_VERSION_HASH_DATE: ${{ steps.myvars.outputs.TAG_DKR_VERSION_HASH_DATE }}
      TAG_GPR_BRANCH_NAME: ${{ steps.myvars.outputs.TAG_GPR_BRANCH_NAME }}
      TAG_GPR_VERSION_BRANCH: ${{ steps.myvars.outputs.TAG_GPR_VERSION_BRANCH }}
      TAG_GPR_VERSION_HASH_ONLY: ${{ steps.myvars.outputs.TAG_GPR_VERSION_HASH_ONLY }}
      TAG_GPR_VERSION_HASH_DATE: ${{ steps.myvars.outputs.TAG_GPR_VERSION_HASH_DATE }}

  # ----------------------------------------------
  # UAT
  # ----------------------------------------------
  uat1_linux-amd64:
    needs: [myvars]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: master
      - uses: zcong1993/setup-timezone@v1.1.2
        with:
          timezone: America/Montreal
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2

      - name: Build UAT on linux/amd64
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          push: false
          load: true # Export to Docker Engine rather than pushing to a registry
          tags: ${{ github.run_id }}
          platforms: linux/amd64

      - name: Checkpoint | Wait for container to run
        timeout-minutes: 2
        run: |
          docker run -d --name ghostUAT -p 2368:2368 -e WEB_URL=http://localhost:2368 -e NODE_ENV=production ${{ github.run_id }}
          echo "--- Wait for ghostUAT --->"
          until $(curl --output /dev/null --silent --head --fail http://localhost:2368); do
            echo "--- ghostUAT is starting..."
            sleep 1
          done;
          echo "--- ghostUAT is running! --->"

      - name: Checkpoint | docker-library tests
        run: |
          curl http://localhost:2368 | grep "Thoughts, stories and ideas"
          git clone --depth 1 https://github.com/docker-library/official-images.git official-images
          cp ./test/config.sh official-images/test/config.sh
          official-images/test/run.sh ${{ github.run_id }}

  uat2_linux-arm64-v8:
    needs: [myvars]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: master
      - uses: zcong1993/setup-timezone@v1.1.2
        with:
          timezone: America/Montreal
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2

      - name: Build linux/arm64/v8
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          push: false
          load: true # Export to Docker Engine rather than pushing to a registry
          tags: ${{ github.run_id }}
          platforms: linux/arm64/v8

      - name: Checkpoint | Wait for container to run
        timeout-minutes: 2
        run: |
          docker run -d --name ghostUAT -p 2368:2368 -e WEB_URL=http://localhost:2368 -e NODE_ENV=production ${{ github.run_id }}
          echo "--- Wait for ghostUAT --->"
          until $(curl --output /dev/null --silent --head --fail http://localhost:2368); do
            echo "--- ghostUAT is starting..."
            sleep 1
          done;
          echo "--- ghostUAT is running! --->"

      - name: Checkpoint | docker-library tests
        run: |
          curl http://localhost:2368 | grep "Thoughts, stories and ideas"
          git clone --depth 1 https://github.com/docker-library/official-images.git official-images
          cp ./test/config.sh official-images/test/config.sh
          official-images/test/run.sh ${{ github.run_id }}

  uat3_linux-arm-v7:
    needs: [myvars]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: master
      - uses: zcong1993/setup-timezone@v1.1.2
        with:
          timezone: America/Montreal
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2

      - name: Build linux/arm/v7
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          push: false
          load: true # Export to Docker Engine rather than pushing to a registry
          tags: ${{ github.run_id }}
          platforms: linux/arm/v7

      - name: Checkpoint | Wait for container to run
        timeout-minutes: 2
        run: |
          docker run -d --name ghostUAT -p 2368:2368 -e WEB_URL=http://localhost:2368 -e NODE_ENV=production ${{ github.run_id }}
          echo "--- Wait for ghostUAT --->"
          until $(curl --output /dev/null --silent --head --fail http://localhost:2368); do
            echo "--- ghostUAT is starting..."
            sleep 1
          done;
          echo "--- ghostUAT is running! --->"

      - name: Checkpoint | docker-library tests
        run: |
          curl http://localhost:2368 | grep "Thoughts, stories and ideas"
          git clone --depth 1 https://github.com/docker-library/official-images.git official-images
          cp ./test/config.sh official-images/test/config.sh
          official-images/test/run.sh ${{ github.run_id }}

  uat4_linux-arm-v6:
    needs: [myvars]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: master
      - uses: zcong1993/setup-timezone@v1.1.2
        with:
          timezone: America/Montreal
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2

      - name: Build linux/arm/v6
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          push: false
          load: true # Export to Docker Engine rather than pushing to a registry
          tags: ${{ github.run_id }}
          platforms: linux/arm/v6

      - name: Checkpoint | Wait for container to run
        timeout-minutes: 2
        run: |
          docker run -d --name ghostUAT -p 2368:2368 -e WEB_URL=http://localhost:2368 -e NODE_ENV=production ${{ github.run_id }}
          echo "--- Wait for ghostUAT --->"
          until $(curl --output /dev/null --silent --head --fail http://localhost:2368); do
            echo "--- ghostUAT is starting..."
            sleep 1
          done;
          echo "--- ghostUAT is running! --->"

      - name: Checkpoint | docker-library tests
        run: |
          curl http://localhost:2368 | grep "Thoughts, stories and ideas"
          git clone --depth 1 https://github.com/docker-library/official-images.git official-images
          cp ./test/config.sh official-images/test/config.sh
          official-images/test/run.sh ${{ github.run_id }}

  # These failed 2021-09-30
  # linux/arm/v6
  # linux/ppc64le
  # linux/s390x
  # windows/amd64
  # linux/arm64/v8
  # windows/arm64/v8
  # https://github.com/firepress-org/ghostfire/issues/57

  # ----------------------------------------------
  # Tests after build
  # ----------------------------------------------
  review_myvars:
    needs: [myvars]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: zcong1993/setup-timezone@v1.1.2
        with:
          timezone: America/Montreal
      - name: Show variables
        run: |
          echo "Final Docker image name:"
          echo "= = = = = = = = = ="
          echo ${{ needs.myvars.outputs.TAG_DKR_BRANCH_NAME }}
          echo ${{ needs.myvars.outputs.TAG_DKR_VERSION_BRANCH }}
          echo ${{ needs.myvars.outputs.TAG_DKR_VERSION_HASH_ONLY }}
          echo ${{ needs.myvars.outputs.TAG_DKR_VERSION_HASH_DATE }}
          echo ${{ needs.myvars.outputs.TAG_GPR_BRANCH_NAME }}
          echo ${{ needs.myvars.outputs.TAG_GPR_VERSION_BRANCH }}
          echo ${{ needs.myvars.outputs.TAG_GPR_VERSION_HASH_ONLY }}
          echo ${{ needs.myvars.outputs.TAG_GPR_VERSION_HASH_DATE }}
          echo
          echo "Core environment variables:"
          echo "= = = = = = = = = ="
          echo "${{ env.DOCKERFILE }} << DOCKERFILE"
          echo "${{ needs.myvars.outputs.BRANCH_NAME }} << BRANCH_NAME"
          echo "${{ needs.myvars.outputs.APP_NAME }} << APP_NAME"
          echo "${{ needs.myvars.outputs.DOCKERHUB_USER }} << DOCKERHUB_USER"
          echo "${{ needs.myvars.outputs.GITHUB_ORG }} << GITHUB_ORG"
          echo "${{ needs.myvars.outputs.GITHUB_REGISTRY }} << GITHUB_REGISTRY"
          echo "${{ needs.myvars.outputs.DKR_PREFIX }} << DKR_PREFIX"
          echo "${{ needs.myvars.outputs.GPR_PREFIX }} << GPR_PREFIX"
          echo "${{ needs.myvars.outputs.VERSION }} << VERSION"
          echo "${{ needs.myvars.outputs.SHORT_HASH_COMMIT }} << SHORT_HASH_COMMIT"
          echo "${{ needs.myvars.outputs.DATE }} << DATE"
          echo "${{ needs.myvars.outputs.VERSION_CI }} << VERSION_CI"
          echo "${{ needs.myvars.outputs.VERSION_BRANCH }} << VERSION_BRANCH"
          echo "${{ needs.myvars.outputs.VERSION_HASH_ONLY }} << VERSION_HASH_ONLY"
          echo "${{ needs.myvars.outputs.VERSION_HASH_DATE }} << VERSION_HASH_DATE"
          echo "${{ needs.myvars.outputs._NOTI_MESSAGE }} << _NOTI_MESSAGE"
          echo
          echo "Environment variables provided Github Actions :"
          echo "= = = = = = = = = ="
          echo "${GITHUB_WORKFLOW} << GITHUB_WORKFLOW"
          echo "${GITHUB_RUN_ID} << GITHUB_RUN_ID"
          echo "${GITHUB_RUN_NUMBER} << GITHUB_RUN_NUMBER"
          echo "${GITHUB_JOB} << GITHUB_JOB"
          echo "${GITHUB_ACTION} << GITHUB_ACTION"
          echo "${GITHUB_ACTOR} << GITHUB_ACTOR"
          echo "${GITHUB_REPOSITORY} << GITHUB_REPOSITORY"
          echo "${GITHUB_EVENT_NAME} << GITHUB_EVENT_NAME"
          echo "${GITHUB_EVENT_PATH} << GITHUB_EVENT_PATH"
          echo "${GITHUB_WORKSPACE} << GITHUB_WORKSPACE"
          echo "${GITHUB_SHA} << GITHUB_SHA"
          echo "${GITHUB_REF} << GITHUB_REF"
          echo "${GITHUB_SERVER_URL} << GITHUB_SERVER_URL"
          echo "${GITHUB_API_URL} << GITHUB_API_URL"
          echo "${GITHUB_GRAPHQL_URL} << GITHUB_GRAPHQL_URL"
          echo "${RUNNER_OS} << RUNNER_OS"
          echo "${RUNNER_TEMP} << RUNNER_TEMP"
          echo "${RUNNER_TOOL_CACHE} << RUNNER_TOOL_CACHE"
          echo "${GITHUB_ACTIONS} << GITHUB_ACTIONS"
